server:
  port: 81

spring:
  application:
    name: hc-order-server

eureka:
  client:
    register-with-eureka: true  #表示将自己注册进eurekaServer
    fetch-registry: true  #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，但是集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka